# This file was generated by GoReleaser. DO NOT EDIT.
cask "eo" do
  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "ea0ba21909f220eb8a0d3106a82e5d57fe29eec4a712201bfa98995e5c8b9733"
      url "https://github.com/evangelischeomroep/eo-cli/releases/download/v#{version}/eo_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "758c30e82dbe9550913234b6f5dfa4b4b33d7bcf802513a7ed3290729463a2e8"
      url "https://github.com/evangelischeomroep/eo-cli/releases/download/v#{version}/eo_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0719025a1be2aa58835c84840b7850cc4870e4e72fba0c0c56e755eed6768c0"
      url "https://github.com/evangelischeomroep/eo-cli/releases/download/v#{version}/eo_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "82ae284198510d461f74dfdb2d39eb4a84abc80c38f8f71e76c6035715d984b1"
      url "https://github.com/evangelischeomroep/eo-cli/releases/download/v#{version}/eo_linux_arm64.tar.gz"
    end
  end

  name "eo"
  desc "Developer CLI for Evangelische Omroep"
  homepage "https://github.com/evangelischeomroep/eo-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on formula: [
    "azure-cli",
  ]

  binary "eo"

  postflight do
    system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/eo"] if OS.mac?
  end
  generate_completions_from_executable "eo", "completion",
                                       shell_parameter_format: :arg,
                                       shells:                 [:bash, :fish, :zsh]

  # No zap stanza required
end
