# This file was generated by GoReleaser. DO NOT EDIT.
cask "eo" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "eo"], chdir: "."
    end
  end

  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "aaf143d4fcefebfa98d47db79e14ff2e0024523c34c99e9dff5e9ee67ce107ff"
      url "https://github.com/evangelischeomroep/eo-cli/releases/download/v#{version}/eo_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "16d1be9be79922de6d06d6ab07ec412e29e344100c508f545c43a183b8b1a0fd"
      url "https://github.com/evangelischeomroep/eo-cli/releases/download/v#{version}/eo_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "03829284306fde9ba06ecd112082146973da9871b42ba90742e22234a92ecba4"
      url "https://github.com/evangelischeomroep/eo-cli/releases/download/v#{version}/eo_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b184940133e52a5d7c1c232778d3f504b0aa9fd066821ddd223b0c95297ee9c"
      url "https://github.com/evangelischeomroep/eo-cli/releases/download/v#{version}/eo_linux_amd64.tar.gz"
    end
  end

  name "eo"
  desc "Developer CLI for Evangelische Omroep"
  homepage "https://github.com/evangelischeomroep/eo-cli"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "azure-cli",
    ]

  binary "eo"

  generate_completions_from_executable "eo", "completion",
    shells: [:bash, :fish, :zsh]

  # No zap stanza required
end
